### ISSUE TITLE
Document changes needed in ee477-designs to run synthesis

### ISSUE THREAD

**Issue by 24jllewis** [andreaskuster/black-parrot#12]
**file:** ee477-designs/toplevels/bp_single_softcore/tcl/filelist.tcl

replace "$BP_FE_DIR/src/v/bp_fe_bht.v" on line 163 with:

    $BP_FE_DIR/src/v/bp_fe_bp.v
    $BP_FE_DIR/src/v/bp_fe_bp_bimodal.v
    $BP_FE_DIR/src/v/bp_fe_bp_gshare.v
    $BP_FE_DIR/src/v/bp_fe_bp_gselect.v

**Comment by andreaskuster** [comment]
The note has been added to the repo: https://github.com/andreaskuster/black-parrot-branch-predictor#modification-in-the-backend-flow
