### ISSUE TITLE
Implement generic bimodal branch predictor

### ISSUE THREAD

**Issue by andreaskuster** [andreaskuster/black-parrot#6]
The current implementation is already a bimodal bp, but we want not only to be able to control the table size, but also the saturation counter bits.

**Comment by andreaskuster** [comment]
I have implemented and tested this version, it is therefore ready to push through the backend flow (more details can be found here: https://github.com/andreaskuster/black-parrot-branch-predictor).

**Comment by andreaskuster** [comment]
At the moment, only the bht_idx_width_p parameter has been routed to the toplevel config file (https://github.com/andreaskuster/black-parrot/blob/6545424601097da8d63bc3ef50ec4658ae6cce2f/bp_common/src/include/bp_common_aviary_pkg.vh#L78).

p_cnt_sat_bits_p has been routed up to the bp_fe_pc_gen module level (https://github.com/andreaskuster/black-parrot/blob/6545424601097da8d63bc3ef50ec4658ae6cce2f/bp_fe/src/v/bp_fe_pc_gen.v#L282)

Feel free to route this up to the bp_single_core_cfg_p. 

This is also a reference for you to show where to adjust the parameters.

**Comment by andreaskuster** [comment]
These are the plots for the parameter grid-search over some Championship Branch Prediction (CBP-5) training traces (I will generate the final ones using matplotlib, but for now these excel versions should be fine):

![grafik](https://user-images.githubusercontent.com/20418060/76345907-63280a00-62c1-11ea-8dcf-9b0a517b2257.png)
![grafik](https://user-images.githubusercontent.com/20418060/76345930-6ae7ae80-62c1-11ea-9ad6-0c1d70f38cb3.png)
![grafik](https://user-images.githubusercontent.com/20418060/76345943-6e7b3580-62c1-11ea-986a-3359682a9f25.png)
![grafik](https://user-images.githubusercontent.com/20418060/76350486-19dbb880-62c9-11ea-8724-fc1a31a6a8af.png)

The different sub-plots are the parameter values for bht_idx_width_p.

My suggestion is we go for:
- bht_idx_width_p = 9 or 12 (or something in between)
- bp_cnt_sat_bits_p = 2 or 3 

You can decide :)
Or you can also do multiple of them and compare the PPA results.

**Comment by andreaskuster** [comment]
Furthermore, i want to encourage you to also run the initial, unmodified design. This is of special interest, since the performance for bht_idx_width_p=9, bp_cnt_sat_bits_p=2 should be the same, but if you **harden** the bht table, we should be better in terms of power and possibly performance/frequency.

**Comment by 24jllewis** [comment]
backend flow complete ✅
