### ISSUE TITLE
Implement gshared branch predictor

### ISSUE THREAD

**Issue by andreaskuster** [andreaskuster/black-parrot#7]

**Comment by andreaskuster** [comment]
I have implemented and model-tested this version. The required files in black-parrot should be updated (at least for hello_world it works).

I am still running the evaluation traces for the parameter evaluation and add the results as soon as this has been finalized.

**Comment by andreaskuster** [comment]
Since it takes a long time to run the (huge) traces with the more complex software model, i add the result that is already done:

![grafik](https://user-images.githubusercontent.com/20418060/76471191-40741f00-63af-11ea-8e08-0dd6b7991444.png)

![grafik](https://user-images.githubusercontent.com/20418060/76471197-4538d300-63af-11ea-94bb-01654dc45888.png)

**Comment by andreaskuster** [comment]
This design has been tested and can be pushed through the backend flow too.

**Comment by 24jllewis** [comment]
backend flow complete ✅
